### ISSUE TITLE
Include URL for each result in the info page

### ISSUE THREAD

**Issue by Georgette** [nodezoo/nodezoo-web#33]
As of today, only the github result includes a URL to a module within git, but it would be nice to have it in all results.

**Use Case: As a user, I'd like to use nodezoo-web to easily navigate to a module within any of the places it exists in the developer eco-system. I'd treat node-zoo as a convenient bookmarking system. As such, I'd like to be able to click a link in the result list and go to associated web page.** 

Additionally, the icons for each result list are rendered as if they are clickable (IE: the pointer changes when mousing over the icon). If we implement this feature, perhaps each icon would link to the associated result URL. If the URL doesn't exist, then perhaps link to the main page of npm/travis/git or at least remove the hover pointer change.

**Comment by mcdonnelldean** [comment]
I'm +1 on this. @Georgette Can you list the data points that are missing here? I will add them to each. I think going with the icons is a great idea and fits in with the search results layout. Feel free to self assign

**Comment by matt-oc** [comment]
@mcdonnelldean @Georgette I was actually in the middle of something very similar until I got dragged away for the msday site, npm and travis modules need to change to send the url to info and then web but its a simple implementation.

**Comment by Georgette** [comment]
We will actually need a http URL for git as well for this, in addition to the git URL (because someone may need the git URL for git clone) We can link the git http url so if the user clicks the link, instead of copy, it will go to the repo.

**Comment by mcdonnelldean** [comment]
This is now in and also being expanded to include ssh url.
