### ISSUE TITLE
Use Prepublish to build the assets

### ISSUE THREAD

**Issue by mcdonnelldean** [nodezoo/nodezoo-web#35]
When we move to dot version we will need to prebuild the site on publish. Will need to use this for it to work correctly. https://www.npmjs.com/package/in-publish

**Comment by mcdonnelldean** [comment]
The /dist folder is git ignored so we will need an `.npmignore` to override this as far as I know.

**Comment by vislamov** [comment]
At this point `npm publish` not publishing `dist` directory to npm even with it included in files array in package.json or with .npmignore ommited in it. Needs more digging on the subject.

**Comment by mcdonnelldean** [comment]
So i think this is because it is ignored in the .gitignore. Yeah dig away see what you come up with.

Kindest Regards,

Dean

**Comment by mcdonnelldean** [comment]
@vislamov @AdrianRossouw We need to chat about this. Basically the .npmignore needs to allow dist for publishing but it also breaks our fuge config. Any more ideas on how to progress this?

**Comment by AdrianRossouw** [comment]
IIRC it will fall back to gitignore if there is no npmignore.
I removed the npmignore, because it only really had the ~* in there.

so just touch and commit the .npmignore?

**Comment by mcdonnelldean** [comment]
I think that should work. I'm pushing releases today so I can check?

Kindest Regards,

Dean

**Comment by vislamov** [comment]
I was trying with .npmignore, the doc says if it's omitted in .npmingnore then it should take it, but didn't work for me, please give it a shot, may be I didn't do it right.

**Comment by mcdonnelldean** [comment]
Closed as complete.
