### ISSUE TITLE
Set Up Linter

### ISSUE THREAD

**Issue by Georgette** [nodezoo/nodezoo-web#37]

**Comment by mcdonnelldean** [comment]
@shanel262 I'm going to assign this to you, can you replicate what is in concorda? Basically we need to be able to lint the front and the back end. They do this [here][concorda]. You will need all the ESLINT plugins and lab.

[concorda]: https://github.com/Concorda/concorda-dashboard/blob/master/package.json#L20

**Comment by mcdonnelldean** [comment]
Done via #48
