### ISSUE TITLE
should not be using uppercase in filenames

### ISSUE THREAD

**Issue by AdrianRossouw** [nodezoo/nodezoo-web#54]
Mac and windows are case __in__sensitive, but linux cares about case deeply.

This is why the following line in `client/containers/info.js` was only breaking when i was trying to build docker containers with it.

```import {TravisInfo} from '../components/TravisInfo'```

The filename was `components/travisInfo.js`, which would work everywhere but on linux.

The node way (tm) to do this is to name the file `components/travis-info.js`.

**Comment by mcdonnelldean** [comment]
@CodeWriterWriter simple start :D

**Comment by AdrianRossouw** [comment]
so the task is to rename the files in git, and change all the requires over.
