### ISSUE TITLE
Linting needs to be added

### ISSUE THREAD

**Issue by matt-oc** [nodezoo/nodezoo-web#63]
nodezoo-search is our baseline

**Comment by Georgette** [comment]
If we need listing, then what am I getting when I run `npm run lint ` and I get reprimanded for bad code style?

**Comment by matt-oc** [comment]
@Georgette We were just going through one by one and making sure each repo had the correct linting files and were linted, web may well be already sorted so this will be closed tomorrow once it has been checked if all is ok (certainly it needs linting anyway)

**Comment by Georgette** [comment]
Yeah, I linted my open PR because I had an outstanding mess to fix :) So it was working great!

**Comment by matt-oc** [comment]
done!
