### ISSUE TITLE
additional info on search results

### ISSUE THREAD

**Issue by Georgette** [nodezoo/nodezoo-web#64]
I'd like to have:

Author Name
Module Description
Home Web Page
Travis Build Status

**Comment by Georgette** [comment]
@matt-oc 

I chose to not use author or home page. Author really isn't important enough to be in a general list of results, and home page is not, on average, part of a particular package. 

Plus I want to save space for additional, and more pressing stuff

**Comment by vislamov** [comment]
@matt-oc 

Can we also have GitHub username that owns the repo? We need it for GitHub buttons.

Thanks in advance!

**Comment by vislamov** [comment]
Added, no worries.

**Comment by mcdonnelldean** [comment]
Closed via #33
