### ISSUE TITLE
Search screen feedback

### ISSUE THREAD

**Issue by mcdonnelldean** [nodezoo/nodezoo-web#68]
Based on the following screenshot,

![screen shot 2016-04-06 at 14 45 58](https://cloud.githubusercontent.com/assets/3625961/14318780/627571ae-fc06-11e5-990e-b17ebc45aea5.png)

- Module names should be all lower case
- Make Star and Fork numbers links (to stars and forks respectively)
- Change `see related modules` to `more info` and link to the info page
- Decrease the overall size of search result elements (they could be half as tall)

**Comment by Georgette** [comment]
Couple of things:

Layout isn't finished, although working on it. 

If related modules isn't going to be an additive search, then should probably just remove it as clicking on the title will drill down like most lists often do. Either that, another icon. 

Any reason to make module names lowercase? I uppercased it because too much text starts to blend. I want to make it easier to to scan names. I could change the font style and size too, but capitalize was a fast dirty method. 

Thanks for feedback :)

**Comment by vislamov** [comment]
Working on it, also I would like to replace our stars and forks with official GitHub buttons. 
https://buttons.github.io/

**Comment by Georgette** [comment]
@vislamov my current pr is for search screen, you are welcome to improve it further but don't want wires to cross.

**Comment by mcdonnelldean** [comment]
@vislamov Negative on those buttons, they will kill the style. Please keep the ones that are there. We are using GitHub's official font for our icons.

@Georgette The lowercase is based on user feedback. I've asked a few people and they've said it looks out of place. Personally I agree, I think lowercase would flow much better.

Agreed on removing the search link, it would free up space for other content now that I think about it. The only reason for not keeping it is because we have nothing of value implemented behind it.

**Comment by matt-oc** [comment]
I think the module names should have the first letter capitalised and the rest lowercase, I tried out all 3 options and that was the best look IMO, but all lowercase is better than all capitals for sure

**Comment by mcdonnelldean** [comment]
I don't mind first capital, I'd prefer all smalls as it fits with the theme better. As long as it is not caps, I'm good.

**Comment by matt-oc** [comment]
I agree either or, but I do like the new Travis button :+1:

**Comment by Georgette** [comment]
How about we at least increase font-size so it aligns better with icons
Comparisons
<img width="729" alt="screen shot 2016-04-07 at 11 30 31 am" src="https://cloud.githubusercontent.com/assets/3783903/14356866/74123628-fcb4-11e5-99b3-43fe528d2acf.png">
<img width="732" alt="screen shot 2016-04-07 at 11 31 02 am" src="https://cloud.githubusercontent.com/assets/3783903/14356867/7412a004-fcb4-11e5-8c66-fd39604de336.png">

**Comment by matt-oc** [comment]
I like it with the bigger font, did you try with first letter capitalised? I would make the name bigger but make the npm version numbers smaller

**Comment by matt-oc** [comment]
What I'm really not sold on is the layout of the github forks stars and watches along the bottom, I think a vertical list may look better but it is very subjective

**Comment by mcdonnelldean** [comment]
@gege that works perfect for me, change away!

Kindest Regards,

Dean

**Comment by mcdonnelldean** [comment]
@gege you can remove the icon if you want too, it'll be a while before we have the analysis to power it

**Comment by vislamov** [comment]
I would agree with @mcdonnelldean on that modules should be lowercased, it's just a common practice, look at the github search results or npm home page, all lowercased.

**Comment by vislamov** [comment]
It would also be nice to have some kind of a live stats on homepage. I wonder if we can pull this data from npm:
![image](https://cloud.githubusercontent.com/assets/5131554/14358653/c857870e-fca2-11e5-9de1-cd0895b6a7ee.png)

**Comment by mcdonnelldean** [comment]
We could do this for our own stats :D

**Comment by mcdonnelldean** [comment]
But it would be nice on the info page too, there is a dump of the available data in the /npm issues page

**Comment by Georgette** [comment]
@matt-oc I agree with you on stars/forks/watches. 

The one thing I'm treading the line on is real estate space. This is a search page, so we want to show as many results as possible, and in such a way that users effectively find what they are looking for. We put too much information, or have the list items take too much real estate, and we slow a user down.

So we need to set a bar of what is the minimum amount of details a user needs available to them from a search perspective, and throw the rest into the drill down. Think of it like a shopping experience. A user is looking for certain things to narrow their options down to a few selections, and then additional information to make a final decision. 

To that end, I'm wondering if the github info is really something that is important over what Vlad just proposed (adding the downloads stats). Download stats tells me how much a module has been vetted. Forks/Watches/Stars is a mixed bag of interpretation, and I'm not sure if it should be a major search detail.

**Comment by mcdonnelldean** [comment]
@Georgette Good points. If you took them out we wouldn't miss to much and the download stats would be a better indication of how the module is doing. Either way the idea is to drill into the info page.

**Comment by mcdonnelldean** [comment]
Closing as redesign is in progress. Feedback from this issue has been passed to the design team.
