### ISSUE TITLE
Search results unavailable unless prior pulled by info page

### ISSUE THREAD

**Issue by vislamov** [nodezoo/nodezoo-web#69]
Just to make a note of it here, when fixed we can close it.

To reproduce:

1. Open home page
2. Type something new that you did not search yet, e.g. "underscore" 
3. Search results page is empty
4. Load /info/underscore URL in the browser
5. Repeat search
6. Search results come up with one results that's been pulled by info

**Comment by mcdonnelldean** [comment]
@vislamov This is expected behaviour, it allows you to run nodezoo and update your local elastic-search without the need for running an updater.

**Comment by vislamov** [comment]
Great!
