### ISSUE TITLE
Better Flexgrid Wanted

### ISSUE THREAD

**Issue by Georgette** [nodezoo/nodezoo-web#70]
The current grid is tedious when doing responsive layout 

What I don't want is to have to do this:

```
className="col-xs-2 col-sm-2 col-md-2 col-lg-2 col-xlg-2"
```
to get an element to have a width of 2 columns

I want to be able to do this, and have it be 2 columns from an xs screen to the largest

``` 
className="col-xs-2"

```

this is more than just quality of life, but the current implementation is far too many queries than needed

As a note, bootstrap 4 is in alpha but uses flexbox and this design

**Comment by mcdonnelldean** [comment]
What is the effort to modify the flexbox grid we already have in the repo? I want to be super careful about adding weight so bootstrap's size would put it at an immediate disadvantage for me. Agree with the need for the above though, it would make the markup easier to read too.
