### ISSUE TITLE
Travis build status button appears even when there is no travis build

### ISSUE THREAD

**Issue by shanel262** [nodezoo/nodezoo-web#76]
On the search page, the travis build status button appears even when there is no travis build available. Only show this when result.travis.connected in search-result.js is equal to true.

![screen shot 2016-04-07 at 14 32 05](https://cloud.githubusercontent.com/assets/10059043/14352792/247ad524-fcce-11e5-932f-1ee5282e373b.png)

**Comment by Georgette** [comment]
Good catch! Knew I was forgetting something!

**Comment by Georgette** [comment]
I actually half-arsed fixed -- needs to probably just display only for pass/failed builds, vs the way I did it.
