### ISSUE TITLE
Placeholders for missing data on info page

### ISSUE THREAD

**Issue by matt-oc** [nodezoo/nodezoo-web#88]
Sometimes fields do not have a value if the user hasn't filled them out in npm or github etc. It might be nice to have placeholder data for this case instead of leaving it blank or not showing the field at all.

Here is an example of fuge missing a homepage:
![screen shot 2016-04-21 at 12 30 52](https://cloud.githubusercontent.com/assets/16647291/14708051/2b24df94-07c0-11e6-9dc3-442dd0f5cd75.png)

**Comment by mcdonnelldean** [comment]
Redesign in progress to fix issues like this.
