### ISSUE TITLE
npm run build failing

### ISSUE THREAD

**Issue by keerthivasan-r** [nodezoo/nodezoo-web#91]
Hi, I have got nodezoo-web forked and got all the i00,i01... branches from upstream and did npm install in each branch and everything worked as expected. I did npm install in the nodezoo-workshop/system directory as well. Everything worked fine. But, when i run npm run build in nodezoo-web directory, it throws the error

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.4.3
npm ERR! npm  v3.8.6

npm ERR! missing script: build
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     ..\MyNodezoo\nodezoo-web\npm-debug.log

Here is Package.json for you reference. 

{
  "name": "nodezoo-web",
  "version": "5.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/rjrodger/nodezoo-web.git"
  },
  "author": "",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/rjrodger/nodezoo-web/issues"
  },
  "homepage": "https://github.com/rjrodger/nodezoo-web",
  "dependencies": {
    "chairo": "1.1.0",
    "handlebars": "4.0.5",
    "hapi": "11.1.2",
    "inert": "3.2.0",
    "vision": "4.0.1",
    "seneca": "https://github.com/senecajs/seneca",
    "seneca-msgstats": "https://github.com/rjrodger/seneca-msgstats",
    "seneca-mesh": "https://github.com/rjrodger/seneca-mesh",
    "seneca-balance-client": "https://github.com/rjrodger/seneca-balance-client"

  }
}
I think there is something that has recently changed. My friend could install it a month ago.

**Comment by Georgette** [comment]
Are you able to update to the latest version? Yours is outdated, and missing scripts.

**Comment by keerthivasan-r** [comment]
I got forked it - https://github.com/nodezoo/nodezoo-web and cloned it to local. Will i be able to 

> npm run build

 in all the branches. i00,i01..i05? npm run build works only in master branch..

**Comment by Georgette** [comment]
Actually, I apologize as I'm not familiar with the workflow of the workshop. The branches are all missing build scripts so the build won't work (as you already know). I'll see what I can do to help :)

**Comment by Georgette** [comment]
@keerthivasan-r In the interim, it looks like you can run 

```
node srv/app-dev.js

``` 

in the `/nodezoo-web` directory to just start the server, which is all it needs. We will look into making sure our repo instructions do what they should do according to workshop :)

**Comment by Georgette** [comment]
@matt-oc Can we put build scripts:  `node srv/app-dev.js` in package.json for branches i00 - i05?

**Comment by keerthivasan-r** [comment]
@Georgette I would just try node srv/app-dev.js and let you know. Thanks for the help. I really appreciate :)

**Comment by keerthivasan-r** [comment]
@Georgette Great, it just run like a charm.Thank you!

**Comment by matt-oc** [comment]
@Georgette I'll do it now and try it out :)

**Comment by matt-oc** [comment]
@Georgette All the main seneca deps are being pulled directly from the github account and this gives a pincannon error when trying to use it because of senenca 2.0. Surely it should have the deps explicitly specified in the json file, 0.2 for balance client and 0.5 for mesh for seneca stuff of this age? I don't know how it is working for anyone that just pulls and installs those branches at the moment.

**Comment by matt-oc** [comment]
@Georgette @keerthivasan-r The problem here is that the build command is not needed for the i branches, I have made an update to the workshop readme to say as much and I have changed all branches here to make the deps explicit to avoid the problems in my above post

**Comment by matt-oc** [comment]
@keerthivasan-r feel free to comment if you have any other issues
